#!/bin/bash
# Build "SMILE MSI.app" — a double-clickable macOS launcher for the desktop app.
#
# Unlike run_app.command (which opens a Terminal window), this produces a real
# .app bundle: no Terminal, shows up in Launchpad/Spotlight, pin-to-Dock-able.
# It wraps the repo's local .venv (bootstrapping it on first launch if missing),
# so it stays in sync with the editable install — no PyInstaller build needed.
#
# Usage:
#   ./scripts/make_macos_app.sh             # build "./SMILE MSI.app"
#   ./scripts/make_macos_app.sh --install   # also copy it into /Applications
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
APP="$REPO/SMILE MSI.app"
MACOS="$APP/Contents/MacOS"
RES="$APP/Contents/Resources"

# Drop any earlier build so only one app remains.
rm -rf "$APP"
mkdir -p "$MACOS" "$RES"

# Single source of truth: read __version__ from the package so the bundle never drifts
# from pyproject / the in-app update check.
VERSION="$(sed -n 's/^__version__ *= *"\([^"]*\)".*/\1/p' "$REPO/smile_msi/__init__.py" | head -1)"
VERSION="${VERSION:-0.0.0}"

# --- Info.plist -------------------------------------------------------------
# NOTE: unquoted heredoc so ${VERSION} expands; the plist body has no other shell metachars.
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>SMILE MSI</string>
  <key>CFBundleDisplayName</key><string>SMILE MSI</string>
  <key>CFBundleIdentifier</key><string>org.smilemsi.app</string>
  <key>CFBundleVersion</key><string>${VERSION}</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>SMILE MSI</string>
  <key>CFBundleIconFile</key><string>SMILE MSI.icns</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
</dict>
</plist>
PLIST

# --- launcher executable (repo path baked in) -------------------------------
# Written with an expanded heredoc so $REPO is frozen at build time; runtime
# variables ($HOME, $date, …) are escaped so they evaluate when launched.
cat > "$MACOS/SMILE MSI" <<LAUNCH
#!/bin/bash
# Auto-generated by scripts/make_macos_app.sh — do not edit by hand.
# Finder-launched apps get a minimal PATH, so add the usual tool locations.
export PATH="\$HOME/.local/bin:\$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

REPO="$REPO"
cd "\$REPO" || exit 1

LOG="\$HOME/Library/Logs/SMILE-MSI.log"
exec >> "\$LOG" 2>&1
echo "--- launch \$(date) ---"

if [ ! -x .venv/bin/python ]; then
  echo "First run: building the environment (a minute or two)…"
  if command -v uv >/dev/null 2>&1; then
    uv venv && uv pip install --python ./.venv/bin/python -e '.[gui]'
  else
    /usr/bin/python3 -m venv .venv && ./.venv/bin/pip install -e '.[gui]'
  fi
fi

# `exec -a "SMILE MSI"` sets argv[0] so the menu bar / Dock / ⌘-Tab show the app name
# instead of "Python" (the bundle execs an external interpreter, so Cocoa would otherwise
# fall back to the process name). Python still finds itself via the real exec path.
exec -a "SMILE MSI" ./.venv/bin/python -m smile_msi.gui
LAUNCH
chmod +x "$MACOS/SMILE MSI"

# --- icon -------------------------------------------------------------------
if [ -f "$REPO/scripts/SMILE MSI.icns" ]; then
  cp "$REPO/scripts/SMILE MSI.icns" "$RES/SMILE MSI.icns"
else
  echo "note: scripts/SMILE MSI.icns not found — run scripts/make_icon.py first for the app icon."
fi

echo "Built $APP"

if [ "${1:-}" = "--install" ]; then
  DEST="/Applications/SMILE MSI.app"
  rm -rf "$DEST"
  cp -R "$APP" "$DEST"
  echo "Installed $DEST"
fi
